import { SCENES } from './sceneCatalog';
import type { AudioAsset } from './types';

/**
 * Every partner audio asset the app can resolve, derived directly
 * from the scene catalog so it can never drift out of sync with
 * DialogueLine.audioAssetId — one entry per dialogue line, for every
 * character, in every scene (not just "the non-default" character,
 * since which character ends up being the partner depends on which
 * one the participant chose to play).
 *
 * Files live under public/audio/<sceneId>/<lineId>.m4a and are
 * generated by scripts/generate-placeholder-audio.ts.
 */
export const AUDIO_ASSETS: AudioAsset[] = SCENES.flatMap((scene) =>
  scene.dialogueLines
    .filter((line): line is typeof line & { audioAssetId: string } => Boolean(line.audioAssetId))
    .map((line) => ({
      id: line.audioAssetId,
      src: `/audio/${scene.id}/${line.id}.m4a`,
      characterId: line.characterId,
    })),
);

export function getAudioAssetById(id: string): AudioAsset | undefined {
  return AUDIO_ASSETS.find((asset) => asset.id === id);
}
